#remote_theme: "mmistakes/minimal-mistakes"
#minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

remote_theme: "just-the-docs/just-the-docs"
# doc https://just-the-docs.com/docs

title                    : "JaCaMo"
search                   : true
search_full_content      : true

include: ["_pages"]
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

nav_external_links:
  - title: "Getting Started"
    url: https://jacamo-lang.github.io/documentation/getting-started/readme.html    
    opens_in_new_tab: true
  - title: "Documentation"
    url: http://jacamo-lang.github.io/jacamo/    
    opens_in_new_tab: true

