# doc https://mmistakes.github.io/minimal-mistakes/docs/configuration/
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"

## Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: ""

## General
title: JaCaMo
description: JaCaMo web site and documentation

atom_feed:
  hide: true
breadcrumbs: true

plugins:
  - jekyll-include-cache

include: ["_pages"]
