remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
include: ["_pages"]
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

