remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

title                    : "JaCaMo"
search                   : true
search_full_content      : true

include: ["_pages"]
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

author_profile: false
