remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

#remote_theme: "just-the-docs/just-the-docs"
# doc https://just-the-docs.com/docs

title: JaCaMo
description: JaCaMo web site and documentation

search_enabled: false

footer_content: ""


# Color scheme supports "light" (default) and "dark"
#color_scheme: dark

include: ["_pages"]
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

nav_external_links:
  - title: "Documentation"
    url: http://jacamo-lang.github.io/jacamo/    
    opens_in_new_tab: true

